### PR TITLE
Fixed unexpected hang on pending_builders_lock (3.x)

### PR DESCRIPTION
**Pull request by slydiman**
The following call may hang for 10..20 minutes w/o any reason (probably due to a bug in DeferredLock) yield self.pending_builders_lock.run(resetPendingBuildersList, new_builders)

1. Refactored _resetPendingBuildersList(), _getPendingBuilders() and _activityLoopIter() to use lock.run() instead of acquire()/release(). Call _activityLoop() directly w/o pending_builders_lock.

2. Removed pending_builders_lock and _sortBuilders() usage at all.

### CODE REVIEW

**Comment by gkistanova** [comment]
Could you mark all the local changes with `LLVM_LOCAL` for one-liners, and `LLVM_LOCAL begin/end` for blocks of code, please? So it would be easier to reconcile local patches later on, when we will merge the mainline changes, please?

I didn't request this for 2.x changes, but it would be nice to have them starting from 3.x.

**Comment by slydiman** [comment]
> Could you mark all the local changes with `LLVM_LOCAL`

I have updated the patch. Please review.

**Comment by slydiman** [comment]
Please note I can confirm that the issue is still present in 3.8.5, can be reproduced locally and this patch fixes it.

**Review by gkistanova — APPROVED** [review]
LGTM.

**Pull request merged**
