### PR TITLE
Fixed unexpected hang on doReconfig (3.x)

### PR DESCRIPTION
**Pull request by slydiman**
`yield self.initLock.acquire()` in doReconfig may hang. Probably `getattr(args[0], lock)` in the decorator @deferredLocked got `self.master.initLock` instead of `self.initLock` somehow in some cases.

### CODE REVIEW

**Comment by gkistanova** [comment]
Hi Dima.

Unless I'm missing something, this is a port of this PR to 3.x, right? I mean we didn't yet get a confirmation that the original problem exists in 3.x.

If so, I'd keep this PR open till the confirmation that the problem still exists.

**Comment by slydiman** [comment]
> If so, I'd keep this PR open till the confirmation that the problem still exists.

Sure

**Comment by gkistanova** [comment]
@slydiman Andrei has mentioned that this problem still exists. So, we do need this patch, don't we?

**Comment by slydiman** [comment]
> Andrei has mentioned that this problem still exists. So, we do need this patch, don't we?

Right. It was expected. We cannot explain the root of this problem. But nothing changed in mainline around these locks. So the problem still exists and we need this patch.

We can reopen this issue https://github.com/buildbot/buildbot/issues/6908 but we have no any new information for investigation.

**Comment by gkistanova** [comment]
Let's commit it then, shall we? Could you rebase this patch, please?

**Pull request merged**
